import { DealBox, MenuItem, StoreSettings, CategoryItem } from '../types';

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  // 1. Branding & Identity
  name: 'PakBite Food & Grill',
  tagline: 'Gourmet Burgers, Sizzling Spicy Meals, Family Feast Boxes & Chilled Desserts',
  logoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=200&auto=format&fit=crop&q=80',
  faviconUrl: '',
  currency: 'Rs.',
  primaryColor: 'amber',

  // 2. Hero & Homepage Content
  heroBannerUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1600&auto=format&fit=crop&q=80',
  heroTitle: 'Unlimited Crispy Food Deals, Family Boxes & Combos',
  heroSubtitle: 'Hand-battered crunchy zinger burgers, sizzling buffalo wings, flame-grilled beef burgers, loaded fries, and refreshing chilled beverages delivered hot to your doorstep.',
  heroBadge: '🔥 EXCLUSIVE DEALS — SAVE UP TO 30% ON FAMILY BOXES',
  heroExploreButtonText: 'Explore All Deals & Boxes',
  heroWhatsappButtonText: 'Order via WhatsApp',

  // 3. Homepage Sections Visibility
  showHero: true,
  showFeaturedDeals: true,
  dealsSectionTitle: '🔥 Food Boxes & Deals',
  dealsSectionSubtitle: 'Specially bundled meal boxes with multiple burgers, fries, nuggets, dips and drinks at big discounts.',
  showMenuSection: true,
  menuSectionTitle: '🍽️ Single Menu Items & Desserts',
  menuSectionSubtitle: 'Choose from individual meals, fiery spicy delicacies, creamy ice creams, and refreshing drinks.',
  showWhyChooseUs: true,
  showFloatingCart: true,

  // 4. Restaurant Information & Contact
  phone: '+92 300 1234567',
  whatsappNumber: '923001234567',
  email: 'orders@pakbitefood.pk',
  address: 'Main Boulevard, Gulberg III / F-7 Blue Area',
  city: 'Lahore / Islamabad',
  openingHours: '12:00 PM - 02:00 AM Daily (Mon - Sun)',
  isOpen: true,
  announcement: '🔥 HOT DEALS: Unlimited Family & Duo Boxes live! Free delivery on orders over Rs. 1,800!',
  showAnnouncement: true,

  // 5. Delivery & Pickup Rules
  enableHomeDelivery: true,
  enablePickup: true,
  deliveryFee: 150,
  freeDeliveryThreshold: 1800,
  estimatedDeliveryTime: '30 - 45 mins',
  minimumOrderAmount: 300,
  deliveryAreas: [
    'Gulberg (Phases I - III)',
    'DHA (Phases 1 - 6)',
    'Model Town & Garden Town',
    'Johar Town & Faisal Town',
    'Bahria Town & Lake City',
    'F-6 / F-7 / Blue Area',
    'G-10 / G-11 / F-10',
    'Saddar / Cantt',
  ],

  // 6. Payments
  enableCashOnDelivery: true,
  enableJazzCash: true,
  jazzCashAccountTitle: 'PakBite Food Restaurant',
  jazzCashAccountNumber: '0300-1234567',
  enableEasypaisa: true,
  easypaisaAccountTitle: 'PakBite Food Restaurant',
  easypaisaAccountNumber: '0300-1234567',
  enableCardPayment: true,

  // 7. WhatsApp Ordering
  enableWhatsappOrdering: true,
  whatsappOrderTemplate: 'Hi PakBite! I want to order from your menu.',

  // 8. Notifications
  orderNotificationSound: true,
  orderNotificationEmail: 'orders@pakbitefood.pk',
  staffAlertPhone: '03001234567',

  // 9. Security
  requireOwnerPin: false,
  ownerPin: '1234',

  // 10. Footer & Social
  footerAboutText: 'PakBite is Pakistan\'s favorite fast food and grill kitchen, serving crispy burgers, spicy chicken wings, unlimited combo boxes, and decadent ice creams.',
  footerCopyright: 'PakBite Food & Grill. All rights reserved.',
  facebookUrl: 'https://facebook.com',
  instagramUrl: 'https://instagram.com',
  tiktokUrl: 'https://tiktok.com',
  youtubeUrl: 'https://youtube.com',
};

export const INITIAL_CATEGORIES: CategoryItem[] = [
  { id: 'cat-dm', name: 'Deal Meal', type: 'product', icon: 'Utensils', displayOrder: 1, isActive: true },
  { id: 'cat-sp', name: 'Spicy Food', type: 'product', icon: 'Flame', displayOrder: 2, isActive: true },
  { id: 'cat-ic', name: 'Ice Cream', type: 'product', icon: 'IceCream', displayOrder: 3, isActive: true },
  { id: 'cat-dr', name: 'Drinks', type: 'product', icon: 'Coffee', displayOrder: 4, isActive: true },
  { id: 'cat-bg', name: 'Burgers & Fast Food', type: 'product', icon: 'Layers', displayOrder: 5, isActive: true },
  { id: 'cat-pz', name: 'Pizza', type: 'product', icon: 'Pizza', displayOrder: 6, isActive: true },
  { id: 'cat-fr', name: 'Fries & Sides', type: 'product', icon: 'Utensils', displayOrder: 7, isActive: true },
  { id: 'cat-fam', name: 'Family Deals', type: 'deal', icon: 'Sparkles', displayOrder: 8, isActive: true },
  { id: 'cat-duo', name: 'Duo Combos', type: 'deal', icon: 'Sparkles', displayOrder: 9, isActive: true },
  { id: 'cat-solo', name: 'Solo Boxes', type: 'deal', icon: 'Sparkles', displayOrder: 10, isActive: true },
  { id: 'cat-mid', name: 'Midnight Deals', type: 'deal', icon: 'Sparkles', displayOrder: 11, isActive: true },
  { id: 'cat-kids', name: 'Kids Boxes', type: 'deal', icon: 'Sparkles', displayOrder: 12, isActive: true },
];

export const INITIAL_DEAL_BOXES: DealBox[] = [
  {
    id: 'deal-family-feast-box',
    name: 'Family Feast Box',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=800&auto=format&fit=crop&q=80',
    description: 'The ultimate royal feast! 4 Crispy Zinger Burgers, 1 Jumbo Seasoned Fries Box, 6 Golden Nuggets with garlic dip, and 4 Chilled Drinks.',
    price: 2499,
    originalPrice: 3450,
    discount: '28% OFF',
    category: 'Family Deals',
    servings: 'Serves 4-5 Persons',
    prepTimeMinutes: 25,
    tag: 'Bestseller',
    isAvailable: true,
    isFeatured: true,
    isActive: true,
    displayOrder: 1,
    includedItems: [
      { id: 'inc-1', name: 'Crispy Zinger Burgers', quantity: 4, unit: 'pcs', note: 'Spicy or Regular' },
      { id: 'inc-2', name: 'Jumbo Seasoned Fries', quantity: 1, unit: 'large box' },
      { id: 'inc-3', name: 'Golden Crispy Nuggets', quantity: 6, unit: 'pcs', note: 'With garlic mayo' },
      { id: 'inc-4', name: 'Chilled Soft Drinks (500ml)', quantity: 4, unit: 'bottles' },
    ],
    addons: [
      { id: 'add-1', name: 'Extra Cheddar Cheese Slice (x4)', price: 180, isAvailable: true },
      { id: 'add-2', name: 'Spicy Peri-Peri Dip Sauce', price: 60, isAvailable: true },
      { id: 'add-3', name: 'Upgrade to 1.5L Jumbo Drink', price: 120, isAvailable: true },
      { id: 'add-4', name: 'Add 6 Extra Spicy Hot Wings', price: 380, isAvailable: true },
    ],
    optionGroups: [
      {
        id: 'opt-drinks-family',
        title: 'Select 4 Drink Flavors',
        required: true,
        choices: [
          { id: 'd-1', name: '4x Coca-Cola' },
          { id: 'd-2', name: '4x Sprite' },
          { id: 'd-3', name: '2x Coke + 2x Sprite' },
          { id: 'd-4', name: '4x Fanta Orange' },
          { id: 'd-5', name: '4x Pakola Ice Cream Soda' },
        ],
      },
      {
        id: 'opt-spice-family',
        title: 'Burger Spice Level',
        required: false,
        choices: [
          { id: 'sp-1', name: 'Classic Crispy (Mild)' },
          { id: 'sp-2', name: 'Spicy Masala' },
          { id: 'sp-3', name: 'Extra Hot Flaming' },
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-mega-burger-deal',
    name: 'Mega Burger Deal',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    description: 'A heavy burger lover dream! 2 Double Patty Beef Cheese Burgers, 2 Crispy Zinger Burgers, 2 Large Crinkle Fries, and 1.5L Coke.',
    price: 2350,
    originalPrice: 3100,
    discount: '24% OFF',
    category: 'Family Deals',
    servings: 'Serves 4 Persons',
    prepTimeMinutes: 22,
    tag: 'Popular',
    isAvailable: true,
    isFeatured: true,
    isActive: true,
    displayOrder: 2,
    includedItems: [
      { id: 'inc-mb-1', name: 'Double Beef Cheese Burgers', quantity: 2, unit: 'pcs', note: 'Smoked BBQ sauce' },
      { id: 'inc-mb-2', name: 'Crunchy Zinger Burgers', quantity: 2, unit: 'pcs' },
      { id: 'inc-mb-3', name: 'Large Crinkle Fries Packs', quantity: 2, unit: 'packs' },
      { id: 'inc-mb-4', name: '1.5 Litre Soft Drink Bottle', quantity: 1, unit: 'bottle' },
    ],
    addons: [
      { id: 'add-mb-1', name: 'Melted Cheddar Cheese Tub', price: 110, isAvailable: true },
      { id: 'add-mb-2', name: 'Jalapeño Poppers (4 Pcs)', price: 290, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-chicken-combo',
    name: 'Chicken Combo',
    image: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800&auto=format&fit=crop&q=80',
    description: 'Golden fried crispy chicken bliss! 4 Pieces Crispy Fried Chicken, 2 Dinner Rolls, 1 Large Fries, 2 Cold Drinks & Garlic Dip.',
    price: 1299,
    originalPrice: 1690,
    discount: '23% OFF',
    category: 'Duo Combos',
    servings: 'Serves 2 Persons',
    prepTimeMinutes: 18,
    tag: 'Crispy Special',
    isAvailable: true,
    isFeatured: true,
    isActive: true,
    displayOrder: 3,
    includedItems: [
      { id: 'inc-cc-1', name: 'Crispy Fried Chicken Pieces', quantity: 4, unit: 'pcs', note: 'Legs & Chest' },
      { id: 'inc-cc-2', name: 'Soft Butter Dinner Rolls', quantity: 2, unit: 'buns' },
      { id: 'inc-cc-3', name: 'Large Salted Fries Box', quantity: 1, unit: 'box' },
      { id: 'inc-cc-4', name: 'Cold Drinks (345ml)', quantity: 2, unit: 'cans' },
      { id: 'inc-cc-5', name: 'Signature Garlic Mayo Dip', quantity: 2, unit: 'cups' },
    ],
    addons: [
      { id: 'add-cc-1', name: 'Extra Crispy Fried Chicken Piece', price: 250, isAvailable: true },
      { id: 'add-cc-2', name: 'Fresh Creamy Coleslaw', price: 120, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-friends-sharing-box',
    name: 'Friends Sharing Box',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80',
    description: 'Made for hanging out! 3 Crunchy Zinger Burgers, 6 Fiery Hot Wings, 1 Loaded Curly Fries Platter, and 3 Chilled Drinks.',
    price: 1799,
    originalPrice: 2400,
    discount: '25% OFF',
    category: 'Duo Combos',
    servings: 'Serves 3 Persons',
    prepTimeMinutes: 20,
    tag: 'Sharing',
    isAvailable: true,
    isFeatured: true,
    isActive: true,
    displayOrder: 4,
    includedItems: [
      { id: 'inc-fs-1', name: 'Crunchy Zinger Burgers', quantity: 3, unit: 'pcs' },
      { id: 'inc-fs-2', name: 'Fiery Buffalo Hot Wings', quantity: 6, unit: 'pcs' },
      { id: 'inc-fs-3', name: 'Loaded Curly Fries Platter', quantity: 1, unit: 'platter' },
      { id: 'inc-fs-4', name: 'Chilled Soft Drinks (345ml)', quantity: 3, unit: 'cans' },
    ],
    addons: [
      { id: 'add-fs-1', name: 'Honey Mustard Dip', price: 50, isAvailable: true },
      { id: 'add-fs-2', name: 'Extra 4 Spicy Wings', price: 280, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-couple-deal',
    name: 'Couple Deal',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    description: 'The duo favorite! 2 Crispy Zinger Burgers, 4 Buffalo Wings, 1 Medium French Fries, and 2 Refreshing Drinks.',
    price: 1199,
    originalPrice: 1550,
    discount: '22% OFF',
    category: 'Duo Combos',
    servings: 'Serves 2 Persons',
    prepTimeMinutes: 15,
    tag: 'Top Pick',
    isAvailable: true,
    isFeatured: true,
    isActive: true,
    displayOrder: 5,
    includedItems: [
      { id: 'inc-cd-1', name: 'Crispy Zinger Burgers', quantity: 2, unit: 'pcs' },
      { id: 'inc-cd-2', name: 'Buffalo Chicken Wings', quantity: 4, unit: 'pcs' },
      { id: 'inc-cd-3', name: 'Medium French Fries', quantity: 1, unit: 'pack' },
      { id: 'inc-cd-4', name: 'Cold Drinks (345ml)', quantity: 2, unit: 'cans' },
    ],
    addons: [
      { id: 'add-cd-1', name: 'Cheese Slice on Burgers (x2)', price: 90, isAvailable: true },
      { id: 'add-cd-2', name: 'Chipotle Dip Sauce', price: 50, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-loaded-meal-box',
    name: 'Loaded Meal Box',
    image: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=800&auto=format&fit=crop&q=80',
    description: 'Heavy single meal box! 1 Mighty Double Zinger, 1 Spicy Masala Fries Pack, 3 Tender Chicken Strips, Honey Mustard Dip & 1 Drink.',
    price: 899,
    originalPrice: 1150,
    discount: 'Save Rs. 250',
    category: 'Solo Boxes',
    servings: 'Serves 1-2 Persons',
    prepTimeMinutes: 15,
    tag: 'Heavy Meal',
    isAvailable: true,
    isFeatured: false,
    isActive: true,
    displayOrder: 6,
    includedItems: [
      { id: 'inc-lm-1', name: 'Mighty Double Zinger Burger', quantity: 1, unit: 'pc' },
      { id: 'inc-lm-2', name: 'Spicy Masala Fries Pack', quantity: 1, unit: 'pack' },
      { id: 'inc-lm-3', name: 'Crispy Chicken Strips', quantity: 3, unit: 'pcs' },
      { id: 'inc-lm-4', name: 'Honey Mustard Dipping Cup', quantity: 1, unit: 'cup' },
      { id: 'inc-lm-5', name: 'Chilled Drink (345ml)', quantity: 1, unit: 'can' },
    ],
    addons: [
      { id: 'add-lm-1', name: 'Extra Cheese Slice', price: 50, isAvailable: true },
      { id: 'add-lm-2', name: 'Upgrade to 500ml Drink', price: 40, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-crispy-chicken-deal',
    name: 'Crispy Chicken Deal',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop&q=80',
    description: '6 Pieces of Crunchy Golden Fried Broast Chicken, 2 Dinner Rolls, 1 Fresh Coleslaw Bowl, and 2 Cold Drinks.',
    price: 1450,
    originalPrice: 1900,
    discount: '24% OFF',
    category: 'Family Deals',
    servings: 'Serves 2-3 Persons',
    prepTimeMinutes: 20,
    tag: 'Crispy Broast',
    isAvailable: true,
    isFeatured: true,
    isActive: true,
    displayOrder: 7,
    includedItems: [
      { id: 'inc-ck-1', name: 'Golden Crispy Fried Chicken', quantity: 6, unit: 'pcs' },
      { id: 'inc-ck-2', name: 'Soft Dinner Rolls', quantity: 2, unit: 'buns' },
      { id: 'inc-ck-3', name: 'Creamy Coleslaw Bowl', quantity: 1, unit: 'bowl' },
      { id: 'inc-ck-4', name: 'Chilled Soft Drinks (345ml)', quantity: 2, unit: 'cans' },
    ],
    addons: [
      { id: 'add-ck-1', name: 'Large Fries Box', price: 180, isAvailable: true },
      { id: 'add-ck-2', name: 'Spicy Garlic Dip', price: 50, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-weekend-special-box',
    name: 'Weekend Special Box',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    description: '1 Medium Chicken Tikka Pizza (9 Inch), 2 Crunchy Zinger Burgers, 1 Large Salted Fries, and 1 Litre Soft Drink.',
    price: 1999,
    originalPrice: 2650,
    discount: '25% OFF',
    category: 'Family Deals',
    servings: 'Serves 3-4 Persons',
    prepTimeMinutes: 25,
    tag: 'Weekend Special',
    isAvailable: true,
    isFeatured: true,
    isActive: true,
    displayOrder: 8,
    includedItems: [
      { id: 'inc-ws-1', name: 'Medium Chicken Tikka Pizza (9")', quantity: 1, unit: 'pizza' },
      { id: 'inc-ws-2', name: 'Crispy Zinger Burgers', quantity: 2, unit: 'pcs' },
      { id: 'inc-ws-3', name: 'Large French Fries Box', quantity: 1, unit: 'box' },
      { id: 'inc-ws-4', name: '1 Litre Soft Drink Bottle', quantity: 1, unit: 'bottle' },
    ],
    addons: [
      { id: 'add-ws-1', name: 'Extra Mozzarella Cheese on Pizza', price: 150, isAvailable: true },
      { id: 'add-ws-2', name: '6 Hot Wings', price: 340, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-jumbo-feast',
    name: 'Jumbo Feast',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&auto=format&fit=crop&q=80',
    description: 'The supreme gathering box! 4 Zinger Burgers, 8 Hot Wings, 8 Golden Nuggets, 2 Large Fries, 1.5L Drink & 3 Dipping Sauces.',
    price: 2999,
    originalPrice: 4100,
    discount: 'Save Rs. 1,100',
    category: 'Family Deals',
    servings: 'Serves 5-6 Persons',
    prepTimeMinutes: 30,
    tag: 'Grand Feast',
    isAvailable: true,
    isFeatured: true,
    isActive: true,
    displayOrder: 9,
    includedItems: [
      { id: 'inc-jf-1', name: 'Supreme Crispy Zinger Burgers', quantity: 4, unit: 'pcs' },
      { id: 'inc-jf-2', name: 'Spicy Buffalo Hot Wings', quantity: 8, unit: 'pcs' },
      { id: 'inc-jf-3', name: 'Golden Crispy Nuggets', quantity: 8, unit: 'pcs' },
      { id: 'inc-jf-4', name: 'Large Seasoned Fries Packs', quantity: 2, unit: 'packs' },
      { id: 'inc-jf-5', name: '1.5L Chilled Soft Drink', quantity: 1, unit: 'bottle' },
      { id: 'inc-jf-6', name: 'Assorted Dipping Sauces (Garlic, Chipotle, Mayo)', quantity: 3, unit: 'cups' },
    ],
    addons: [
      { id: 'add-jf-1', name: 'Upgrade to 2x 1.5L Drinks', price: 140, isAvailable: true },
      { id: 'add-jf-2', name: 'Extra 4 Zinger Burgers', price: 1400, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-super-saver-deal',
    name: 'Super Saver Deal',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    description: 'Everyday pocket-friendly value! 1 Crispy Chicken Burger, 1 Regular Salted French Fries, and 1 Chilled 345ml Soft Drink.',
    price: 599,
    originalPrice: 790,
    discount: '24% OFF',
    category: 'Solo Boxes',
    servings: 'Serves 1 Person',
    prepTimeMinutes: 12,
    tag: 'Budget Friendly',
    isAvailable: true,
    isFeatured: false,
    isActive: true,
    displayOrder: 10,
    includedItems: [
      { id: 'inc-ss-1', name: 'Crispy Chicken Burger', quantity: 1, unit: 'pc' },
      { id: 'inc-ss-2', name: 'Regular Salted Fries', quantity: 1, unit: 'pack' },
      { id: 'inc-ss-3', name: 'Chilled Soft Drink (345ml)', quantity: 1, unit: 'can' },
    ],
    addons: [
      { id: 'add-ss-1', name: 'Add Cheddar Cheese Slice', price: 50, isAvailable: true },
      { id: 'add-ss-2', name: 'Garlic Mayo Dip', price: 40, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-midnight-box',
    name: 'Midnight Cravers Pizza & Burger Box',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    description: 'Late night cravings solved! 1 Small Pan Pizza, 1 Classic Zinger Burger, Fries, 4 Nuggets and 1 Drink.',
    price: 1550,
    originalPrice: 2100,
    discount: '26% OFF',
    category: 'Midnight Deals',
    servings: 'Serves 2-3 Persons',
    prepTimeMinutes: 20,
    tag: 'Night Special',
    isAvailable: true,
    isFeatured: false,
    isActive: true,
    displayOrder: 11,
    includedItems: [
      { id: 'inc-m1', name: 'Small Chicken Tikka Pizza (7 inch)', quantity: 1, unit: 'pizza' },
      { id: 'inc-m2', name: 'Crispy Zinger Burger', quantity: 1, unit: 'pc' },
      { id: 'inc-m3', name: 'Golden Fried Chicken Nuggets', quantity: 4, unit: 'pcs' },
      { id: 'inc-m4', name: 'Crinkle Fries Box', quantity: 1, unit: 'box' },
      { id: 'inc-m5', name: '500ml Chilled Soda', quantity: 1, unit: 'bottle' },
    ],
    addons: [
      { id: 'add-m1', name: 'Extra Mozzarella on Pizza', price: 140, isAvailable: true },
      { id: 'add-m2', name: 'Garlic Butter Crust', price: 80, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-kids-box',
    name: 'Junior Fun Meal Box',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&auto=format&fit=crop&q=80',
    description: 'Mild, fun and delicious! 1 Mini Mild Chicken Burger, 4 Tender Nuggets, Smiley Smiles Fries, Juice Box & Surprise Toy.',
    price: 649,
    originalPrice: 850,
    discount: '23% OFF',
    category: 'Kids Boxes',
    servings: 'Serves 1 Kid',
    prepTimeMinutes: 12,
    tag: 'Kids Favorite',
    isAvailable: true,
    isFeatured: false,
    isActive: true,
    displayOrder: 12,
    includedItems: [
      { id: 'inc-k1', name: 'Junior Mild Chicken Burger', quantity: 1, unit: 'pc' },
      { id: 'inc-k2', name: 'Crispy Tender Nuggets', quantity: 4, unit: 'pcs' },
      { id: 'inc-k3', name: 'Smiley Potato Fries', quantity: 1, unit: 'pack' },
      { id: 'inc-k4', name: 'Mango / Apple Fruit Juice', quantity: 1, unit: 'tetra pack' },
      { id: 'inc-k5', name: 'Toy Collectible', quantity: 1, unit: 'surprise' },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // ================= 1. DEAL MEAL CATEGORY ================= //
  {
    id: 'm-dm-1',
    name: 'Combo Supreme Zinger Meal',
    description: '1 Crispy Zinger Burger, 1 Regular Salted Fries & 1 Soft Drink 345ml.',
    price: 749,
    originalPrice: 899,
    category: 'Deal Meal',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Single Meal',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dm-2',
    name: 'Student Shawarma & Drink Deal',
    description: '1 Jumbo Chicken Shawarma Roll, 1 Seasoned Fries & 1 Chilled Mint Lemonade.',
    price: 499,
    originalPrice: 650,
    category: 'Deal Meal',
    image: 'https://images.unsplash.com/photo-1633321702518-7feccafb94d5?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Single Combo',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dm-3',
    name: 'Crispy Broast Quarter Deal',
    description: '1 Quarter Fried Broast Chicken (Chest/Leg), 1 Dinner Bun, Fries & Garlic Sauce.',
    price: 620,
    originalPrice: 750,
    category: 'Deal Meal',
    image: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Quarter Broast',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dm-4',
    name: 'Double Patty Beef Meal',
    description: '1 Gourmet Beef Cheeseburger, 1 Masala Fries & 1 Soft Drink 345ml.',
    price: 890,
    originalPrice: 1050,
    category: 'Deal Meal',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Beef Combo',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dm-5',
    name: 'Nuggets Express Meal',
    description: '6 Golden Crispy Nuggets, 1 Regular Fries, Garlic Mayo Dip & 1 Soft Drink.',
    price: 560,
    originalPrice: 690,
    category: 'Deal Meal',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Snack Meal',
    createdAt: new Date().toISOString(),
  },

  // ================= 2. SPICY FOOD CATEGORY (10 items) ================= //
  {
    id: 'm-sp-1',
    name: 'Spicy Chicken Burger',
    description: 'Whole spicy marinated crispy chicken breast fillet, spicy chili-mayo sauce, jalapeños, and crunchy lettuce in toasted sesame bun.',
    price: 480,
    originalPrice: 580,
    category: 'Spicy Food',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    isSpicy: true,
    tag: 'Spicy 🔥',
    portion: 'Single Burger',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-sp-2',
    name: 'Fiery Zinger Burger',
    description: 'Double fried crispy chicken thigh dipped in fiery ghost pepper sauce, jalapeños & spicy chipotle slaw.',
    price: 590,
    originalPrice: 690,
    category: 'Spicy Food',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    isSpicy: true,
    tag: 'Extra Hot 🔥🔥',
    portion: '1 Large Burger',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-sp-3',
    name: 'Hot & Crispy Chicken (2 Pcs)',
    description: 'Golden fried chicken pieces marinated in a fiery blend of crushed red peppers and paprika, served with spicy garlic dip.',
    price: 450,
    originalPrice: 540,
    category: 'Spicy Food',
    image: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    isSpicy: true,
    tag: 'Crispy Hot',
    portion: '2 Pieces',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-sp-4',
    name: 'Spicy Chicken Wings (6 Pcs)',
    description: 'Jumbo chicken wings glazed in sizzling hot chili-buffalo sauce and garnished with toasted chili flakes.',
    price: 490,
    originalPrice: 580,
    category: 'Spicy Food',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    isSpicy: true,
    tag: 'Buffalo Hot',
    portion: '6 Wings',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-sp-5',
    name: 'Peri Peri Chicken (Half)',
    description: 'Flame-grilled tender half chicken basted with authentic spicy African bird eye peri-peri marinade and fresh lime.',
    price: 790,
    originalPrice: 950,
    category: 'Spicy Food',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    isSpicy: true,
    tag: 'Flame Grilled',
    portion: 'Half Chicken',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-sp-6',
    name: 'Spicy Loaded Fries',
    description: 'Crispy French fries drenched in spicy melted cheddar cheese, chopped jalapeños and spicy minced chicken.',
    price: 480,
    originalPrice: 580,
    category: 'Spicy Food',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    isSpicy: true,
    tag: 'Hot Platter',
    portion: 'Sharing Platter',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-sp-7',
    name: 'Hot Chicken Wrap',
    description: 'Crispy fiery chicken tenders, sliced green chilies, lettuce, diced tomatoes & spicy chipotle sauce in a warm grilled tortilla.',
    price: 420,
    originalPrice: 490,
    category: 'Spicy Food',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    isSpicy: true,
    tag: 'Spicy Wrap',
    portion: '1 Wrap',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-sp-8',
    name: 'Fire Chicken Sandwich',
    description: 'Toasted artisan sub sandwich stuffed with shredded spicy smoked chicken, melted chili gouda cheese & hot peri sauce.',
    price: 450,
    originalPrice: 530,
    category: 'Spicy Food',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    isSpicy: true,
    tag: 'Hot Sandwich',
    portion: '1 Sandwich',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-sp-9',
    name: 'Spicy Nuggets (6 Pcs)',
    description: 'Tender chicken nuggets with a crunchy spicy chili-flake coating, served with signature spicy dip.',
    price: 350,
    originalPrice: 420,
    category: 'Spicy Food',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    isSpicy: true,
    tag: 'Spicy Snack',
    portion: '6 Pieces',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-sp-10',
    name: 'Chilli Cheese Fries',
    description: 'Crispy French fries layered with warm spicy cheddar cheese sauce, fiery chili relish, and pickled jalapeños.',
    price: 440,
    originalPrice: 520,
    category: 'Spicy Food',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    isSpicy: true,
    tag: 'Cheesy Hot',
    portion: 'Platter',
    createdAt: new Date().toISOString(),
  },

  // ================= 3. ICE CREAM CATEGORY (10 items - Separate) ================= //
  {
    id: 'm-ic-1',
    name: 'Chocolate Ice Cream',
    description: 'Rich, creamy dark Dutch chocolate ice cream scoop served in a crisp waffle cup with chocolate shavings.',
    price: 260,
    originalPrice: 320,
    category: 'Ice Cream',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Single Scoop Cup',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-ic-2',
    name: 'Vanilla Ice Cream',
    description: 'Classic silky Madagascar vanilla bean ice cream scoop finished with golden caramel drizzle.',
    price: 220,
    originalPrice: 280,
    category: 'Ice Cream',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Single Scoop Cup',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-ic-3',
    name: 'Strawberry Ice Cream',
    description: 'Refreshing creamy pink strawberry ice cream made with real strawberry chunks and sweet berry swirl.',
    price: 240,
    originalPrice: 300,
    category: 'Ice Cream',
    image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Single Scoop Cup',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-ic-4',
    name: 'Mango Ice Cream',
    description: 'Pure tropical bliss! Velvety ice cream prepared with pure natural Pakistani Chaunsa mango pulp.',
    price: 250,
    originalPrice: 310,
    category: 'Ice Cream',
    image: 'https://images.unsplash.com/photo-1505394033641-40c6ad1178d7?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Single Scoop Cup',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-ic-5',
    name: 'Oreo Ice Cream',
    description: 'Creamy sweet vanilla cream loaded with generous chunks of crushed Oreo cookies and chocolate drizzle.',
    price: 290,
    originalPrice: 350,
    category: 'Ice Cream',
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28be0?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Waffle Cone',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-ic-6',
    name: 'Chocolate Chip Ice Cream',
    description: 'Smooth and silky sweet cream churned with crisp dark chocolate flakes and chocolate fudge.',
    price: 270,
    originalPrice: 330,
    category: 'Ice Cream',
    image: 'https://images.unsplash.com/photo-1560008581-09826d1de69e?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Single Scoop Cup',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-ic-7',
    name: 'Caramel Sundae',
    description: 'Double scoop Madagascar vanilla ice cream drenched in warm buttery caramel sauce, whipped cream & roasted nuts.',
    price: 390,
    originalPrice: 480,
    category: 'Ice Cream',
    image: 'https://images.unsplash.com/photo-1549395156-e0c1fe6fc7a5?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Sundae Glass',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-ic-8',
    name: 'Brownie Sundae',
    description: 'Warm baked dark chocolate fudge brownie topped with Belgian chocolate ice cream, hot chocolate sauce & almonds.',
    price: 490,
    originalPrice: 590,
    category: 'Ice Cream',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Dessert Bowl',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-ic-9',
    name: 'Cookie & Cream',
    description: 'Gourmet rich ice cream churned with chocolate sandwich biscuit crumbs, chocolate chips and cookie garnish.',
    price: 320,
    originalPrice: 380,
    category: 'Ice Cream',
    image: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Double Scoop Cup',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-ic-10',
    name: 'Mixed Ice Cream Cup',
    description: 'Triple scoop celebration cup with chocolate, strawberry and vanilla scoops topped with cherry & wafer roll.',
    price: 380,
    originalPrice: 460,
    category: 'Ice Cream',
    image: 'https://images.unsplash.com/photo-1516559828984-fb3b99548b21?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Triple Scoop Platter',
    createdAt: new Date().toISOString(),
  },

  // ================= 4. DRINKS CATEGORY (12 items - Separate) ================= //
  {
    id: 'm-dr-1',
    name: 'Karak Chai',
    description: 'Freshly brewed traditional Pakistani strong milk tea slowly simmered with crushed green cardamom.',
    price: 140,
    originalPrice: 180,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Clay Matka Cup',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dr-2',
    name: 'Cold Drink (500ml)',
    description: 'Ice-cold carbonated beverage of your choice (Coca-Cola, Sprite, Fanta, Pakola, Mountain Dew).',
    price: 130,
    originalPrice: 150,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: '500ml Bottle',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dr-3',
    name: 'Lemonade',
    description: 'Freshly squeezed lemon juice with chilled sparkling water, pure cane sugar syrup, and mint garnish.',
    price: 260,
    originalPrice: 320,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Chilled Glass',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dr-4',
    name: 'Fresh Juice',
    description: '100% natural, freshly squeezed seasonal fruit juice served ice cold without artificial flavorings.',
    price: 350,
    originalPrice: 420,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: '400ml Glass',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dr-5',
    name: 'Mineral Water (500ml)',
    description: 'Pure spring drinking water bottle, served chilled.',
    price: 90,
    originalPrice: 100,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: '500ml Sealed Bottle',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dr-6',
    name: 'Milkshake (Royal Nutella)',
    description: 'Thick creamy vanilla ice cream shake blended with rich Nutella chocolate and roasted hazelnuts.',
    price: 450,
    originalPrice: 520,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: '500ml Jar',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dr-7',
    name: 'Mango Shake',
    description: 'Lush ripe Chaunsa mango pulp blended with rich vanilla ice cream and chilled creamy milk.',
    price: 420,
    originalPrice: 490,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: '500ml Glass',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dr-8',
    name: 'Strawberry Shake',
    description: 'Fresh farm strawberries blended with thick strawberry ice cream and topped with whipped cream.',
    price: 410,
    originalPrice: 480,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1553787499-6f9133860278?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: '500ml Glass',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dr-9',
    name: 'Chocolate Shake',
    description: 'Decadent dark chocolate ice cream shake with rich chocolate ganache and chocolate sprinkles.',
    price: 430,
    originalPrice: 500,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: '500ml Glass',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dr-10',
    name: 'Mint Lemonade',
    description: 'Handcrafted crushed fresh mint leaves, zesty lemon juice, black salt, and sparkling ice soda.',
    price: 280,
    originalPrice: 340,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Chilled Glass',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dr-11',
    name: 'Fresh Orange Juice',
    description: '100% pure freshly squeezed seasonal orange citrus juice full of natural vitamins.',
    price: 360,
    originalPrice: 430,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Fresh 400ml Glass',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-dr-12',
    name: 'Iced Tea',
    description: 'Brewed black Ceylon tea infused with fresh lemon juice, mint leaves, and served over ice.',
    price: 240,
    originalPrice: 290,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Tall Iced Glass',
    createdAt: new Date().toISOString(),
  },

  // ================= 5. BURGERS & FAST FOOD ================= //
  {
    id: 'm-bg-1',
    name: 'Classic Crunch Zinger Burger',
    description: 'Whole tender chicken breast battered in crispy secret spices, fresh iceberg lettuce and creamy mayo.',
    price: 490,
    originalPrice: 580,
    category: 'Burgers & Fast Food',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Single Burger',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-bg-2',
    name: 'Double Smokey Beef Cheese Burger',
    description: 'Two 100% prime beef patties, double melted cheddar, caramelized onions and smoked BBQ mayo in toasted brioche bun.',
    price: 790,
    originalPrice: 920,
    category: 'Burgers & Fast Food',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Double Patty',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-bg-3',
    name: 'Grilled Chicken Patty Burger',
    description: 'Juicy herb-seasoned grilled chicken patty with fresh tomatoes, cheddar cheese and honey mustard.',
    price: 460,
    originalPrice: 540,
    category: 'Burgers & Fast Food',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Grilled Burger',
    createdAt: new Date().toISOString(),
  },

  // ================= 6. PIZZA ================= //
  {
    id: 'm-pz-1',
    name: 'Chicken Tikka Supreme Pizza (Medium 9")',
    description: 'Traditional tandoori spiced chicken chunks, onions, bell peppers, melted mozzarella & signature pizza sauce.',
    price: 1150,
    originalPrice: 1400,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: true,
    portion: 'Medium 9-Inch',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-pz-2',
    name: 'Fajita Sensation Pizza (Medium 9")',
    description: 'Mexican spiced chicken strips, jalapenos, sweet corn, green peppers, double mozzarella & oregano crust.',
    price: 1190,
    originalPrice: 1450,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Medium 9-Inch',
    createdAt: new Date().toISOString(),
  },

  // ================= 7. FRIES & SIDES ================= //
  {
    id: 'm-fr-1',
    name: 'Crispy Golden French Fries (Large)',
    description: 'Signature golden crinkle-cut fries lightly salted and fried to crispy perfection.',
    price: 250,
    originalPrice: 300,
    category: 'Fries & Sides',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: 'Large Box',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm-fr-2',
    name: 'Crispy Chicken Tenders (4 Pcs)',
    description: 'Hand-breaded juicy tender chicken breast strips served with signature honey mustard sauce.',
    price: 380,
    originalPrice: 460,
    category: 'Fries & Sides',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isFeatured: false,
    portion: '4 Tenders',
    createdAt: new Date().toISOString(),
  },
];

export const SAMPLE_FOOD_IMAGES = [
  { label: 'Burger & Fries Combo Box', url: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=800&auto=format&fit=crop&q=80' },
  { label: 'Crispy Zinger & Wings Feast', url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80' },
  { label: 'Solo Box & Strips', url: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=800&auto=format&fit=crop&q=80' },
  { label: 'Pizza & Fast Food Box', url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80' },
  { label: 'Cricket Match Party Platter', url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&auto=format&fit=crop&q=80' },
  { label: 'Kids Junior Fun Box', url: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&auto=format&fit=crop&q=80' },
  { label: 'Broast & Chicken Platter', url: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800&auto=format&fit=crop&q=80' },
  { label: 'Sizzling Spicy Wings Box', url: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop&q=80' },
  { label: 'Shawarma Roll & Fries Box', url: 'https://images.unsplash.com/photo-1633321702518-7feccafb94d5?w=800&auto=format&fit=crop&q=80' },
  { label: 'Ice Cream & Brownie Box', url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&auto=format&fit=crop&q=80' },
  { label: 'Chocolate Shake & Sundae', url: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=80' },
  { label: 'Fresh Lemonade & Juices', url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=80' },
];

export const DEAL_CATEGORIES = [
  'All Deals & Boxes',
  'Family Deals',
  'Duo Combos',
  'Solo Boxes',
  'Midnight Deals',
  'Kids Boxes',
];

export const MENU_CATEGORIES = [
  'All Menu',
  'Deal Meal',
  'Spicy Food',
  'Ice Cream',
  'Drinks',
  'Burgers & Fast Food',
  'Pizza',
  'Fries & Sides',
];
